{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrs.fullname" . }}-api
  labels:
    {{- include "vrs.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: {{ include "vrs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
{{- end }}
