{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrs.fullname" . }}-console
  labels:
    {{- include "vrs.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  selector:
    app.kubernetes.io/name: {{ include "vrs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console
  ports:
    - name: http
      port: {{ .Values.console.service.port }}
      targetPort: http
{{- end }}
