{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vrs.fullname" . }}-console
  labels:
    {{- include "vrs.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vrs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: console
  template:
    metadata:
      labels:
        {{- include "vrs.labels" . | nindent 8 }}
        app.kubernetes.io/component: console
        vrs.ai/gpu-role: "none"
    spec:
      containers:
        - name: console
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: console-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
            - name: console-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: console-config
          configMap:
            name: {{ include "vrs.fullname" . }}-console
{{- end }}
