{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrs.fullname" . }}-metrics
  labels:
    {{- include "vrs.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    app.kubernetes.io/name: {{ include "vrs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
{{- end }}
